### PR TITLE
attempt to fix #519

### LINKED ISSUE #519: moveit_ros_planning failing to build on indigo
http://jenkins.ros.org/view/IbinS32/job/ros-indigo-moveit-ros-planning_binarydeb_saucy_i386/69/console

It looks like a missing dependency declaration. 

```
-- Using these message generators: gencpp;genlisp;genpy
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'eigen3'
--   found eigen3, version 3.2.0
-- Found Eigen: /usr/include/eigen3  
-- Eigen found (include: /usr/include/eigen3)
CMake Error at /usr/share/cmake-2.8/Modules/FindQt4.cmake:1382 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:25 (find_package)


-- Configuring incomplete, errors occurred!
dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo returned exit code 1
make[1]: *** [override_dh_auto_configure] Error 2
```

### PR DESCRIPTION
**Pull request by mikeferguson**
I think this is all we need to fix #519, but we should make sure the devel job builds, if so, re-release indigo.

### CODE REVIEW

**Comment by mikeferguson** [comment]
Heads up to @davetcoleman @isucan

**Comment by davetcoleman** [comment]
Thanks @mikeferguson

**Comment by isucan** [comment]
thanks, 0.6.1 released

**Comment by mikeferguson** [comment]
Ok, looks to be built: http://jenkins.ros.org/job/ros-indigo-moveit-ros-planning_binarydeb_saucy_amd64/

**Comment by mikeferguson** [comment]
but move_group is failing.... http://jenkins.ros.org/job/ros-indigo-moveit-ros-move-group_binarydeb_saucy_amd64/67/

**Comment by mikeferguson** [comment]
move_group fix should be in https://github.com/ros-planning/moveit_ros/pull/522

**Pull request merged**
