### PR TITLE
rviz gui for planner parameters

### PR DESCRIPTION
**Pull request by rhaschke**
Inspired by #625 I worked on an extension of the rviz MotionPlanningFrame to show and edit parameters of a selected planning algorithm. As a MoveIt novice, I found it particularly hard to know about available parameters and where to adjust them.

This PR adds a new rviz::PropertyTreeWidget to the "Context" panel. Available planner parameters are retrieved and set through two new ROS services provided by the `move_group` node. This nodes employs the methods get/setPlannerConfigurations() of the `planning_interface`.

Unfortunately, these methods provide an untyped parameter map only (string -> string), such that the gui interface cannot provide type checking too.
If the map would employ something like QVariant(), we could have type-safe user interaction...

I added the new services to the MoveGroupQueryPlannersService capability to have it loaded by default.

@sachinchitta @isucan Please comment on that extension to further improve it.

### CODE REVIEW

**Comment by rhaschke** [comment]
This PR requires the new message and services types suggested by [PR #15 in moveit_msgs](https://github.com/ros-planning/moveit_msgs/pull/15).

**Comment by sachinchitta** [comment]
Could you move this PR to jade-devel? I also opened a jade-devel branch for moveit_msgs for the corresponding PR there.

**Comment by rhaschke** [comment]
Sure. Should we apply all those recent indigo commits first? Would you 
prefer a merge or (squashed?) cherry pick?

**Comment by sachinchitta** [comment]
Cherry picked would be good.

**Comment by davetcoleman** [comment]
Great idea - a much needed introspection tool

**Comment by rhaschke** [comment]
@sachinchitta @isucan @davetcoleman 
I merged moveit-ros' indigo-devel branch into jade-devel. (After cherry-picking all merge commits manually, I noticed that finally indigo-devel and jade-devel were identical. Hence I decided to merge directly, which better reflects the actual history.)

**Comment by rhaschke** [comment]
Replaced by #628.

**Pull request closed without merging**
