### PR TITLE
Allow planning groups to have more than one tip, with addition.

### PR DESCRIPTION
**Pull request by hersh**
This is a copy of #431 with an additional commit.  Previously #431 did not actually call the new KinematicsBase::supportsGroup() function.  This just adds that call and some associated error messaging.

### CODE REVIEW

**Comment by davetcoleman** [comment]
+1, that was needed indeed

**Comment by hersh** [comment]
I ran pr2_moveit_tests with this change, and they all passed.  I also tried it with a dummy implementation of supportsGroup() which purposely fails on a group called "left-arm" and works on anything else, and that showed the error message as it should.

**Comment by 130s** [comment]
Thank you all the lot! Is this going to be released into Hydro/Indigo or
both? Thanks again in advance.

**Comment by hersh** [comment]
This will likely be released into both, but not for a few weeks.  We need to get some experience using it and make sure it doesn't break anything else before we release it.

**Comment by davetcoleman** [comment]
Indigo support: 
https://groups.google.com/forum/#!searchin/moveit-users/indigo/moveit-users/0NuSq8_TgLE/uU8k5gKCHAkJ

**Pull request merged**
