### PR TITLE
Modifications for warehouse_ros refactor

### PR DESCRIPTION
**Pull request by TheBrewCrew**
This changes moveit_warehouse to be compatible with the refactor of warehouse_ros that I have done in ros-planning/warehouse_ros#22.  This enables MoveIt! to be built on non LTS Ubuntu while allowing MongoDB to be dynamically loaded with pluginlib if warehouse_ros_mongo is installed.

### CODE REVIEW

**Comment by mikeferguson** [comment]
@davetcoleman @130s -- once we get the new warehouse_ros released into j+k, we will need to get this into j+k as well

**Comment by 130s** [comment]
Ok. I briefly tried rebasing `jade-devel` to this branch and got multitude of conflicts that didn't seem easy to resolve. I'll have to try again with care but it'll be later this week if that's ok.

**Comment by davetcoleman** [comment]
I just used this branch to get moveit [compiling on Kinetic](https://github.com/ros-planning/moveit_ros/issues/695) - I think its time to merge this long standing PR. However I found one compile-time bug - it seems a new file [warehouse_services.cpp](https://github.com/ros-planning/moveit_ros/commits/jade-devel/warehouse/warehouse/src/warehouse_services.cpp) was added since you created this PR and so it does not initalize RobotStateStorage correctly. The fix is [here](https://github.com/davetcoleman/moveit_ros/commit/1d86e4984171ae03024954d8ca3396836250cc80). Could you take a look at that, and also rebase `jade-devel` onto this branch?

Thanks!

**Comment by mikeferguson** [comment]
@davetcoleman -- Connor was an intern with us last summer -- I'm not sure he is really active on MoveIt at all right now -- so I would suggest that one of the maintainers do a cherry-pick/rebase/whatever to get a new PR open (as @130s did with Connor's other PR)

**Comment by davetcoleman** [comment]
will do after my other PRs from today get merged

**Comment by davetcoleman** [comment]
Superseded by https://github.com/ros-planning/moveit_ros/pull/699

**Pull request closed without merging**
