### PR TITLE
Added move_group capability for clearing octomap.

### PR DESCRIPTION
**Pull request by hersh**
In addition to the capability and service, this adds a button to the motion planning rviz plugin as well.

This requires users to add the capability to their move_group.launch files before it will work.

I don't know much about the interactions between move_group components, so if this is likely to cause trouble please speak up.  I have tested this with a single camera writing to the octomap and it worked for me.

### CODE REVIEW

**Comment by davetcoleman** [comment]
> This requires users to add the capability to their move_group.launch files before it will work.

Shoul I add the line to the Setup Assistant? What is that line?

**Comment by hersh** [comment]
move_group/ClearOctomapService

**Comment by davetcoleman** [comment]
Thanks. I just noticed that there is a name discrepancy in this Service from all the rest:

```
move_group/MoveGroupCartesianPathService
move_group/MoveGroupExecuteService
move_group/MoveGroupKinematicsService
move_group/MoveGroupMoveAction
move_group/MoveGroupPickPlaceAction
move_group/MoveGroupPlanService
move_group/MoveGroupQueryPlannersService
move_group/MoveGroupStateValidationService
move_group/MoveGroupGetPlanningSceneService
move_group/ClearOctomapService
```

Shouldn't it be `MoveGroupClearOctomapService` ? This has not been released yet so can still be changed.

**Comment by hersh** [comment]
I just couldn't stand yet another stutter ("move_group/MoveGroup"), so I left it off.  If you think it's important, you can add it.  (Why do we use namespaces if the first characters of every class are going to be a copy of the namespace?)

**Comment by davetcoleman** [comment]
I agree its redundant. I guess I don't care either way.

**Comment by davetcoleman** [comment]
I'll just stick with it: https://github.com/ros-planning/moveit_setup_assistant/issues/98

**Pull request merged**
