### PR TITLE
[Cherrypick Indigo-->Jade][moveit joy] Add friendlier error message

### PR DESCRIPTION
**Pull request by 130s**
#639

### CODE REVIEW

**Comment by 130s** [comment]
Also cherry-picking https://github.com/ros-planning/moveit_ros/pull/680 since the same error seems to be occurring ([from travis](https://travis-ci.org/ros-planning/moveit_ros/builds/133232581#L3481)).

**Comment by 130s** [comment]
Travis passed. Merging since this is cherry-pick, which means the targeted PR (#639) was already approved on another branch.

**Comment by davetcoleman** [comment]
added a test, nice!

**Comment by mikeferguson** [comment]
This test is failing on the buildfarm: http://build.ros.org/job/Jdev__moveit_ros__ubuntu_trusty_amd64/14/

**Comment by mikeferguson** [comment]
Actually, its passing, but producing no output:

```
11:56:23 [xUnit] [INFO] - Converting '/home/jenkins-slave/workspace/Jdev__moveit_ros__ubuntu_trusty_amd64/catkin_workspace/test_results/moveit_ros_robot_interaction/gtest-locked_robot_state_test.xml' .
11:56:23 [xUnit] [INFO] - Converting '/home/jenkins-slave/workspace/Jdev__moveit_ros__ubuntu_trusty_amd64/catkin_workspace/test_results/moveit_ros_visualization/rostest-test_moveit_joy.xml' .
11:56:23 [xUnit] [ERROR] - The result file '/home/jenkins-slave/workspace/Jdev__moveit_ros__ubuntu_trusty_amd64/catkin_workspace/test_results/moveit_ros_visualization/rosunit-moveit_joy.xml' for the metric 'GoogleTest' is empty. The result file has been skipped.
```

@tfoote @wjwwood any idea how to fix this? I've never seen this before and I'm trying to resolve it quickly so we can release and fix https://github.com/ros-planning/moveit_ros/issues/681

**Comment by tfoote** [comment]
It looks like the unit tests are registered but do not run anything: 

```
11:56:16   /opt/ros/jade/share/rostest/cmake/../../../bin/rostest --pkgdir=/tmp/catkin_workspace/src/moveit_ros/visualization --package=moveit_ros_visualization --results-filename test_moveit_joy.xml --results-base-dir /tmp/catkin_workspace/test_results /tmp/catkin_workspace/src/moveit_ros/visualization/test/moveit_joy.test 
11:56:17 ... logging to /home/buildfarm/.ros/log/rostest-040a8f379f67-4666.log
11:56:17 [ROSUNIT] Outputting test results to /tmp/catkin_workspace/test_results/moveit_ros_visualization/rostest-test_moveit_joy.xml
11:56:19 testmoveit_joy ... ok
11:56:19 
11:56:19 [ROSTEST]-----------------------------------------------------------------------
11:56:19 
11:56:19 
11:56:19 SUMMARY
11:56:19 [32m * RESULT: SUCCESS[0m
11:56:19  * TESTS: 0
11:56:19  * ERRORS: 0
11:56:19  * FAILURES: 0
```

Thus it generates empty xml which looks suspicious to the test output validation.

**Comment by wjwwood** [comment]
I don't think it will make a difference with respect to your issue on the farm, but based on the documentation:

http://docs.ros.org/jade/api/catkin/html/howto/format2/rostest_configuration.html#cmakelists-txt

I'd say the `add_rostest` should be inside of a `if (CATKIN_ENABLE_TESTING)` block and that `rostest` should be separately `find_package(...)`'ed within the same block.

Again, I don't think it fix the error about an empty gtest result. I haven't seen that before myself.

**Pull request merged**
