### PR TITLE
Added install rule to install moveit_joy.py.

### PR DESCRIPTION
**Pull request by UltronDestroyer**

### CODE REVIEW

**Comment by davetcoleman** [comment]
lgtm

**Comment by 130s** [comment]
Just wondering why do we need this when there's already [setup.py](https://github.com/ros-planning/moveit_ros/blob/55def098cbffd0f309c6630c5098d173e738ea84/visualization/setup.py) set up?

**Comment by 130s** [comment]
Just wondering why do we need this when there's already [setup.py](https://github.com/ros-planning/moveit_ros/blob/55def098cbffd0f309c6630c5098d173e738ea84/visualization/setup.py) set up that installs `moveit_joy.py`?

**Comment by 130s** [comment]
Asked https://github.com/ros-planning/moveit_ros/issues/638

**Pull request merged**
