### PR TITLE
Implement issue #630: Extended planning_interface::PlanningSceneInterface

### PR DESCRIPTION
**Pull request by corot**
I have added these two methods:

```
std::map<std::string, moveit_msgs::CollisionObject> getObjects(const std::vector<std::string> &object_ids);

std::map<std::string, moveit_msgs::AttachedCollisionObject> getAttachedObjects(const std::vector<std::string> &object_ids);
```

I need them because I'm interested on the collision object size (for grasping it) and not only in its pose. In both cases, if object_ids is omitted, all [attached] objects are returned.

And I modified this one to optionally provide colors for each object:

```
void addCollisionObjects(const std::vector<moveit_msgs::CollisionObject> &collision_objects,
                         const std::vector<moveit_msgs::ObjectColor> &object_colors = std::vector<moveit_msgs::ObjectColor>()) const;
```

I have noticed that, if I publish the colors separatedly, some times it doesn't work and the RViz plugin shows all with the default green. Publishing together with the objects themselves, it always work (or so it looks by now!).

I will also PR the corresponding Python versions.

### CODE REVIEW

**Comment by corot** [comment]
Seems to me like maintainers of this repo (and moveit in general) are really overwhelmed by work, as PRs accumulates with scarce merges, even simple ones as this one.

I can lend a helping hand, if needed.

**Comment by davetcoleman** [comment]
Indeed that seems to be the case with us

**Comment by 130s** [comment]
@corot Could you rebase to `origin/indigo-devel` so that at lease we can go through Travis test.

**Comment by corot** [comment]
Sorry @130s,  do you mean merging current origin/indigo-devel into my corot:extended_psi branch so it contains the latest code?

**Comment by 130s** [comment]
@corot Yes :)

**Comment by corot** [comment]
sorry for the delay.... done. I also updated the [python cousin](https://github.com/ros-planning/moveit_commander/pull/40) of this PR

**Comment by v4hn** [comment]
Hey corot,

Thanks for the contribution!
A full +1 for adding `getObjects` and `getAttachedObjects`, these have been missing for sure.
However, you mixed these additions with changes to `addCollisionObjects` and I really don't like to see this function changed. This is for two reasons:

(1.) adding the optional parameter changes the ABI and people using the function will have to recompile their code or they get segfaults/ an undefined symbol. I know some other devs don't care about ABI changes, but I do not like to see them in indigo at least.

(2.) This function is meant to provide a _simple_ way to add objects to the planning scene.
If you wish to add colors or allow collisions, why not publish a PlanningScene.msg yourself?
After all `addCollisionObjects` is just a simple wrapper...

Could you remove the color-addition to `addCollisionObjects` from this request and add it to a new request (maybe targetting `jade-devel`)?

**Comment by corot** [comment]
@v4hn, thanks for your impressive reactivenes!
Ok, I get the point, so I reverted color info argument. However,  I will include back when I repeat this PR on kinetic (end of month, probably) because A) is much compact than publishing a separated PlanningScene.msg  B) much more important: sometimes it doesn't work!  (and so the RViz plugin shows all with the default green)

**Comment by v4hn** [comment]
@corot: Thanks!
If something doesn't work that's either due to a bug or due to misuse of an interface.
Please feel free to open an issue for that problem :-)
I don't see the problem yet with sending a PlanningScene message that contains your collision objects and their color without using `addCollisionObjects` at all.

**Comment by v4hn** [comment]
All checks passed and it provides a neat addition to the interface. Thanks a lot!

**Comment by corot** [comment]
ok, I'll test back setting colors separately. Was long time a go that I noticed the problem; maybe I just did something stupid, or it got fixed in the last months...

btw, just a reminder that I did a [python cousin](https://github.com/ros-planning/moveit_commander/pull/40) of this PR

**Comment by davetcoleman** [comment]
> However, I will include back when I repeat this PR on kinetic (end of month, probably) because A) is much compact than publishing a separated PlanningScene.msg B) much more important: sometimes it doesn't work! (and so the RViz plugin shows all with the default green)

+10! I've always used my MoveItVisualTools package to add collision objects, but now that I'm attempting to use PlanningSceneInterface the lack of color is sorely needed.

**Comment by v4hn** [comment]
If we do include the optional color parameter, we should also add it to the apply* functions (and maybe add some more add* convenience functions as I did for apply* while we're at it...).
As an alternative, we could also add an object_colors attribute to the PSI that will be used with the next request.
We use this concept with the MoveGroupInterface already.

**Comment by davetcoleman** [comment]
SGTM. The default single-color transparent green is very annoying (though the color can be changed within the Rviz gui)

**Pull request merged**
