### PR TITLE
[joy.py] Installed python file might not be executable.

### PR DESCRIPTION
**Pull request by 130s**
```
$ ll /opt/ros/indigo/lib/python2.7/dist-packages/moveit_ros_visualization/moveit_joy.py
-rw-r--r-- 1 root root 23K Apr 12 12:01 /opt/ros/indigo/lib/python2.7/dist-packages/moveit_ros_visualization/moveit_joy.py
$ dpkg -p ros-indigo-moveit-ros-visualization | grep Ver
Version: 0.7.1-0trusty-20160618-030142-0700
```

### CODE REVIEW

**Comment by 130s** [comment]
Initially I pulled too many wrong commits by mistake, which is fixed now.

**Comment by v4hn** [comment]
Hey Isaac,

I think this should actually be `install(PROGRAMS` instead of `FILES`.
CMake takes care of the rest then.

**Comment by 130s** [comment]
How cool is that! Updated.

**Comment by 130s** [comment]
@v4hn looks like you cherry-picked this into `indigo-devel`. Thanks for doing that!
It'd be even nicer if you mentioned having done so. Thanks!

**Comment by v4hn** [comment]
On Mon, Jun 20, 2016 at 01:59:06PM -0700, Isaac I.Y. Saito wrote:

> @v4hn looks like you cherry-picked this into `indigo-devel`. Thanks for doing that!
> It'd be even nicer if you mentioned having done so. Thanks!

Ah, yes. Sorry, I forgot to add a notice. -.-"
Shouldn't happen of course.

**Comment by davetcoleman** [comment]
If you are backporting a change I think it should be through the PR mechanism so that someone else can double check it

**Comment by 130s** [comment]
Back to original issue, which is how `moveit_ros.py` gets installed, I remember [I asked a question](http://answers.ros.org/question/224546/to-execute-modules-as-scripts-in-catkin/) (and am still waiting for answers). I guess we need to use "catkin-way" for installing python.

**Pull request merged**
