### PR TITLE
Updated doxygen comment in TrajectoryExecutionManager.

### PR DESCRIPTION
**Pull request by hersh**
Added some hard-earned knowledge to the docs.

### CODE REVIEW

**Comment by davetcoleman** [comment]
Always +1 to more documentation

**Comment by adolfo-rt** [comment]
I have never used this method, and I still don't understand well th description. From the name `waitForExecution()`, I would interpret that the call blocks until all pending trajectories have finished execution. Why is it that execution _stops_ when called after `pushAndExecute()`?.

**Comment by hersh** [comment]
Because the class is broken.  I don't have time to fix it, so I just added a comment to hopefully save someone else the time I wasted.

**Comment by adolfo-rt** [comment]
Copy that. Then how about opening an issue describing what's broken?. It would also be useful to reflect that something is broken in this doc enhancement. When I originally read it, I had the impression that the current behavior was OK, only lacking better documentation, and that the problem was me not understanding it.

**Comment by hersh** [comment]
Yeah, of course you are right. I was pull-requesting in anger.  Sigh.

**Comment by adolfo-rt** [comment]
Thanks for filing #468.

**Pull request merged**
