### PR TITLE
Created new Rviz trajectory playback display

### PR DESCRIPTION
**Pull request by davetcoleman**
I've implemented phase one of https://github.com/ros-planning/moveit_ros/issues/478, creating a separate Rviz plugin for displaying trajectories. For now it has the exact same features as the original 'Planned Path' property panel.

In a separate branch I've also removed the duplicate functionality from the main Rviz MotionPlanningPlugin. This change is not included in this PR (this instead creates duplicate code / functionality). However, I'm not sure what to do in this other branch... I made a mistake in thinking it would be easy to 'nestle' one Rviz Display inside another. Turns out, it appears I cannot (easily) place this new plugin inside the old MotionPlanning one. Any advice is greatly appreciated @hersh @isucan 

screenshot from 2015-01-08 01 30 14

### CODE REVIEW

**Comment by isucan** [comment]
+1

**Comment by davetcoleman** [comment]
You didn't address my duplicate code question...

**Comment by isucan** [comment]
How did you get rid of the duplicate code? (I assumed that would be a next PR). Are you having difficulty implementing that? (we should avoid code duplication wherever possible). Maybe include a link to that branch?

**Comment by davetcoleman** [comment]
Currently this PR creates duplicate code, yes. I'm having difficulty combining the two displays.

The problem is that I created a new Rviz Display, and it seems like I can't put this new display (the trajectory one) inside the Motion Planning Display.

I might be able to do it if I created a new helper class...

**Comment by davetcoleman** [comment]
I figured it out, though it was tricky: https://github.com/ros-planning/moveit_ros/pull/551

**Pull request closed without merging**
