### PR TITLE
release lock when loading octomap from file fails

### PR DESCRIPTION
**Pull request by jonbinney**
ioan you didn't catch my stupid error!

### CODE REVIEW

**Comment by davetcoleman** [comment]
jeez ioan!

**Comment by isucan** [comment]
:) 
Actually, can we use a scoped lock? That will unlock in case of exceptions too? (merging this for now anyway)

**Comment by jonbinney** [comment]
does a scoped lock also let you distinguish between locking for reading and locking for writing?

**Comment by isucan** [comment]
try this:
boost::shared_lockboost::shared_mutex slock;

**Pull request merged**
