### PR TITLE
New IK plugin via ROS service calls, supporting kinematic trees

### PR DESCRIPTION
**Pull request by davetcoleman**
**Note:** _This commit will not build until the pending PR for moveit_core is merged ros-planning/moveit_core#149_

Create a new plugin in `moveit_ros_planning` similar to `kdl_kinematics_plugin` that creates an interface between `moveit_core`'s `KinematicBase` and standard ROS Service calls. Also supports the new kinematics trees - solving with more than one tip frame and pose. 

This is used for lisp-based whole body kinematic solvers at the JSK lab, and could also be used for robots like Baxter that have their own IK solver accessible via a ROS Service call.

### CODE REVIEW

**Comment by hersh** [comment]
@davetcoleman can you clean this up so it doesn't have Sachin's release commits in it?  It makes it hard to see what you've changed.

**Comment by davetcoleman** [comment]
I don't understand why it is showing those... the release comments have
already been merged into hydro-devel so why does it appear that I am adding
them again? Seems like a github bug... I tried making a new PR already and
it still had them.

On Wednesday, March 5, 2014, hersh notifications@github.com wrote:

> @davetcoleman https://github.com/davetcoleman can you clean this up so
> it doesn't have Sachin's release commits in it? It makes it hard to see
> what you've changed.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ros-planning/moveit_ros/pull/434#issuecomment-36654301
> .

## 

:: dave | 251.463.2345 c

**Comment by adolfo-rt** [comment]
Did you merge your branch against hydro-devel before doing the PR?. If so, consider rebasing (instead of merging) your work on top of hydro-devel. This will rewrite the history of your commits so they get applied on top of the current hydro-devel head. Or you can just create a new branch from current hydro-devel and cherry-pick the relevant changesets from your `ros_service_ik_plugin` branch. Either solution should work fine.

**Comment by davetcoleman** [comment]
Re-factored here: https://github.com/ros-planning/moveit_ros/pull/436

**Pull request closed without merging**
