### PR TITLE
perception: addng locks to planning scene monitor so it doesn't you know...

### LINKED ISSUE #291: move_group crashing occassionally
This happens when it is using the depth map updater. Here's a backtrace:
#0  0x00007ffff2cdd430 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#1  0x00007ffff2cdd50b in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#2  0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#3  0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#4  0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#5  0x00007ffff2cdd50b in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.s---Type <return> to continue, or q <return> to quit---
o
#6  0x00007ffff2cdd50b in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#7  0x00007ffff2cdd565 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#8  0x00007ffff2cdd550 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#9  0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#10 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#11 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

---Type <return> to continue, or q <return> to quit---
   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#12 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#13 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#14 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#15 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#16 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#17 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostrea---Type <return> to continue, or q <return> to quit---

m&) const ()
   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#18 0x00007ffff2cdd4f5 in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#19 0x00007ffff2cdd5bc in octomap::OcTreeDataNode<float>::writeValue(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#20 0x00007ffff2cdd612 in octomap::OcTreeBaseImpl<octomap::OcTreeNode, octomap::AbstractOccupancyOcTree>::writeData(std::ostream&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#21 0x00007ffff2cbe70e in planning_scene::PlanningScene::getPlanningSceneMsgOctomap(moveit_msgs::PlanningScene_std::allocator<void >&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
#22 0x00007ffff2cc83cd in planning_scene::PlanningScene::getPlanningSceneDiffMsg(moveit_msgs::PlanningScene_std::allocator<void >&) const ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene.so
---Type <return> to continue, or q <return> to quit---
#23 0x00007ffff6937747 in planning_scene_monitor::PlanningSceneMonitor::scenePublishingThread() ()

   from /home/sachinc/code/hydro-pick-place/devel/lib/libmoveit_planning_scene_monitor.so
#24 0x00007ffff44bdce9 in thread_proxy ()

   from /usr/lib/libboost_thread.so.1.46.1
#25 0x00007ffff7135e9a in start_thread (arg=0x7fffd559f700)

```
at pthread_create.c:308
```
#26 0x00007ffff5881ccd in clone ()

```
at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
```
#27 0x0000000000000000 in ?? ()

### LINKED ISSUE #514: planning_scene_monitor can crash when clearing Octomap due to mutex issue
If the clear Octomap interface is used, there's a thread safety issue which can result in a crash. According to gdb, the PlanningSceneMonitor is calling `clearOctomap()` in one thread, and the PlanningScene is calling `getPlanningSceneMsgOctomap()` in another. `clearOctomap()` is destructing OcTreeNodes, while `getPlanningSceneMsgOctomap()` is writing them. I can't figure out where to correctly lock/unlock the mutex for the octree, however.

### PR DESCRIPTION
**Pull request by jbohren**
...... die.

fixes #291 
fixes #514 

I'm testing this now, but it's been running for 20 minutes and has yet to crash, I'm going to leave it running all night.

### CODE REVIEW

**Comment by jbohren** [comment]
yeah, this still fails in `planning_scene::PlanningScene::getPlanningSceneDiffMsg`

**Comment by mikeferguson** [comment]
Sounds like it is at least somewhat more reliable though?

**Comment by jbohren** [comment]
Well it's still segfaulting.

**Comment by jbohren** [comment]
Closing for now.

**Pull request closed without merging**
