### PR TITLE
Filter Point Cloud without Occupancy Map

### PR DESCRIPTION
**Pull request by davetcoleman**
This new plugin allows you to republish a point cloud that has filtered out the robot's links, and it run much faster than the current occupancy map filter since it does not use the occupancy map.

See https://github.com/ros-planning/moveit_ros/pull/523#issuecomment-63455744

### CODE REVIEW

**Comment by isucan** [comment]
Any way we can make this an option in the other filter? Or is the approach different here?

**Comment by davetcoleman** [comment]
The approach is the same, I just removed all the parts concerning octomaps. Not a bad idea, except the other one is named octomap filter so its a misnomer.

**Comment by isucan** [comment]
I see. I like the option you propose, but I'd rather avoid code duplication. Can you rename & make the code you removed optional instead?

**Comment by MiroslavKohut** [comment]
Hi 

At first I have to say thank you for awesome work you do. 
Unfortunatelly I have problem with implementing your plugin. I am using indigo-devel Moveit with Ubuntu 14.04 but when I am trying to compile Moveit with your plugin I am getting following error: 

> In file included from /opt/ros/indigo/include/class_loader/class_loader_core.h:39:0,
>                  from /opt/ros/indigo/include/class_loader/class_loader_register_macro.h:33,
>                  from /opt/ros/indigo/include/class_loader/class_loader.h:39,
>                  from /home/mirec/catkin_ws/src/moveit/moveit/moveit_ros/perception/pointcloud_filter/src/plugin_init.cpp:37:
> /opt/ros/indigo/include/class_loader/meta_object.h: In instantiation of ‘B\* class_loader::class_loader_private::MetaObject<C, B>::create() const [with C = occupancy_map_monitor::PointCloudFilter; B = occupancy_map_monitor::OccupancyMapUpdater]’:
> /home/mirec/catkin_ws/src/moveit/moveit/moveit_ros/perception/pointcloud_filter/src/plugin_init.cpp:40:114:   required from here
> /opt/ros/indigo/include/class_loader/meta_object.h:193:17: error: cannot allocate an object of abstract type ‘occupancy_map_monitor::PointCloudFilter’
>       return new C;
>                  ^
> In file included from /home/mirec/catkin_ws/src/moveit/moveit/moveit_ros/perception/pointcloud_filter/src/plugin_init.cpp:38:0:
> /home/mirec/catkin_ws/src/moveit/moveit/moveit_ros/perception/pointcloud_filter/include/moveit/pointcloud_filter/pointcloud_filter.h:53:7: note:   because the following virtual functions are pure within ‘occupancy_map_monitor::PointCloudFilter’:
>  class PointCloudFilter : public OccupancyMapUpdater
>        ^
> In file included from /home/mirec/catkin_ws/src/moveit/moveit/moveit_ros/perception/pointcloud_filter/include/moveit/pointcloud_filter/pointcloud_filter.h:47:0,
>                  from /home/mirec/catkin_ws/src/moveit/moveit/moveit_ros/perception/pointcloud_filter/src/plugin_init.cpp:38:
> /home/mirec/catkin_ws/src/moveit/moveit/moveit_ros/perception/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_updater.h:78:23: note:     virtual occupancy_map_monitor::ShapeHandle occupancy_map_monitor::OccupancyMapUpdater::excludeShape(const ShapeConstPtr&)
>    virtual ShapeHandle excludeShape(const shapes::ShapeConstPtr &shape) = 0;
>                        ^
> make[2]: **\* [moveit/moveit/moveit_ros/perception/pointcloud_filter/CMakeFiles/moveit_pointcloud_filter.dir/src/plugin_init.cpp.o] Error 1
> make[1]: **\* [moveit/moveit/moveit_ros/perception/pointcloud_filter/CMakeFiles/moveit_pointcloud_filter.dir/all] Error 2
> make[1]: **\* Waiting for unfinished jobs....

Any ideas what could cause an error ? I am working with ros just for year and I understand basic concepts but my programming skill are still not good enough to find solution or understand what could cause this error

Thank you for your time and help.

**Comment by davetcoleman** [comment]
I haven't touched this plugin for 2 years and do not know what might have changes in the code base to break it. I am no longer using the plugin and, based on @isucan's feedback I abandoned it for lack of interest. Sorry I can't help you further.

**Pull request closed without merging**
