### PR TITLE
Modifications for warehouse_ros refactor

### PR DESCRIPTION
**Pull request by davetcoleman**
Rebase https://github.com/ros-planning/moveit_ros/pull/607 with latest jade-devel, along with small fix for a new file that was added since the original PR was created last August. Great work @TheBrewCrew 

Required for https://github.com/ros-planning/moveit_ros/issues/695

@mikeferguson

### CODE REVIEW

**Comment by 130s** [comment]
Travis job is failing because it tries to build `moveit_ros` (yes this repo itself) from source from `jade-devel` branch.

**Comment by davetcoleman** [comment]
@130s so there is a bug in the .travis.yml script? should we switch to industrial_ci?

**Comment by rhaschke** [comment]
Simply looks like the file `database_connection.h` wasn't committed:

```
In file included from /home/travis/ros/ws_moveit/src/moveit_ros/warehouse/warehouse/src/moveit_message_storage.cpp:37:0:
/home/travis/ros/ws_moveit/src/moveit_ros/warehouse/warehouse/include/moveit/warehouse/moveit_message_storage.h:40:47: fatal error: warehouse_ros/database_connection.h: No such file or directory
 #include <warehouse_ros/database_connection.h>
```

The `travis.yml` is fine.

**Comment by davetcoleman** [comment]
it builds fine locally and in my Docker containers though

**Comment by rhaschke** [comment]
Probably you have this include file locally, but missed to submit it.
When I checkout this PR, I don't see this file.

**Comment by davetcoleman** [comment]
The file exists... https://github.com/ros-planning/warehouse_ros/blob/jade-devel/include/warehouse_ros/database_connection.h

I'll look into this further later, I've been focusing on an [industrial_ci bug](https://github.com/ros-industrial/industrial_ci/pull/70) today in moveit_core

**Comment by davetcoleman** [comment]
This passes using new [CI script](https://github.com/ros-planning/moveit_core/issues/309). Ready to merge.

**Comment by rhaschke** [comment]
+1

**Comment by v4hn** [comment]
Thanks for your work!

**Pull request merged**
