### PR TITLE
Publish organized pointcloud to filtered_cloud topic

### PR DESCRIPTION
**Pull request by garaemon**
Add two parameter for sensor:
- fitlered_cloud_use_color: If this parameter is set to True, filtered_cloud will have rgb field.
- filtered_cloud_keep_organized: If this parameter is set to True, filtered_cloud will be a organized pointcloud. which keeps structure of depth image.

In order to implement it, several methods are updated to template method to take into account point type.
- non filtered pointcloud

a
- filtered pointcloud (organized and colored)

b

based on 
- https://github.com/ros-planning/moveit_ros/pull/518 
- https://github.com/ros-planning/moveit_ros/pull/517

### CODE REVIEW

**Comment by garaemon** [comment]
BTW, I found that it is time consuming computation to update occupancy map.
Publising rate of filtered cloud may be about 1Hz when the pointcloud is not so near from the robot.

So I wrote a plugin only to filter pointcloud wothout occupancy map and it can publish pointcloud in 30Hz.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/389

Is the plugin worth to send PR to moveit_ros?

**Comment by mikeferguson** [comment]
@garaemon I will take a closer look at the code later this weekend -- but one comment I wanted to make was that if we are going to merge this feature into hydro, we will also need to merge a similar feature into indigo -- but that there is no PCL left in the indigo version, so you might want to take a look at how that implementation will be different.

**Comment by garaemon** [comment]
I see, I will write indigo PR if you see this feature is useful.

2014年11月2日日曜日、Michael Fergusonnotifications@github.comさんは書きました:

> @garaemon https://github.com/garaemon I will take a closer look at the
> code later this weekend -- but one comment I wanted to make was that if we
> are going to merge this feature into hydro, we will also need to merge a
> similar feature into indigo -- but that there is no PCL left in the indigo
> version, so you might want to take a look at how that implementation will
> be different.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-planning/moveit_ros/pull/523#issuecomment-61381450
> .

## 

from iPhone

**Comment by davetcoleman** [comment]
Hi @garaemon, you are very correct that maintaining the octomap is slow and unnecessary for just filtering point clouds. I made this plugin myself last month (`pointcloud_filter` I call it) but I didn't create a pull request for it. I used it for some ICRA data I sent in, so I think it is pretty reliable and it works on Indigo without PCL. Let me know if you think it is better than yours, or if you want to improve yours with mine.

https://github.com/davetcoleman/moveit_ros/compare/_poincloud_filter_plugin

**Comment by garaemon** [comment]
> so I think it is pretty reliable and it works on Indigo without PCL

Yes, It's a good feature to use indigo but I'm still using hydro...

> Let me know if you think it is better than yours, or if you want to improve yours with mine.

I believe yours is better than mine. 

Problem of self-filtering in ROS is that, [the original one](http://wiki.ros.org/robot_self_filter) is lost and now it's hosted in [pr2_navigation](https://github.com/PR2/pr2_navigation/tree/hydro-devel/pr2_navigation_self_filter). However it does not support dae mesh files.

So I think moveit can be a good alternative for robot_self_filter, however it may be too heavy for the purpose of just filtering.

**Comment by sachinchitta** [comment]
This is against hydro - please port and open against jade if needed.

**Pull request closed without merging**
