### PR TITLE
Moved motion_planning_rviz_plugin_frame into scrollarea

### PR DESCRIPTION
**Pull request by dornhege**
Addresses ros-planning/moveit#13.

The drawback that I can see is that right now it doesn't seem to grow as large as necessary, if there is enough space.

Functionality should still be the same, but should be tested.

### CODE REVIEW

**Comment by v4hn** [comment]
... that was meant to be one of the World MoveIt Day Issues. :D
Well, looks like there are still some issues to look into, according to your description :)

Thanks for your work!

**Comment by dornhege** [comment]
Oops... I'm gonna be on vacation on World MoveIt Day, so just leave it open. That was easy enough to just do like this. Someone could handle the merge/port then. Probably should be done for jade/kinetic too, if this works.

**Comment by davetcoleman** [comment]
Screenshot? 

Also I wouldn't discourage anyone from addressing issues pre-WMD

**Comment by v4hn** [comment]
On Thu, Aug 04, 2016 at 08:32:49AM -0700, Christian Dornhege wrote:

> Oops... I'm gonna be on vacation on World MoveIt Day, so just leave it open.
> That was easy enough to just do like this.

That's the problem with many things I thought about adding as issues for WMD.
In some cases it take even longer to describe them in an issue than to simply _do_ them.

As long as MoveIt! improves along the way, I'm fine with it!

On Thu, Aug 04, 2016 at 10:14:15AM -0700, Dave Coleman wrote:

> Also I wouldn't discourage anyone from addressing issues pre-WMD

Didn't want to do that, that's why I added happy smileys :-)

@dornhege would be great if you could continue this before WMD.

**Comment by dornhege** [comment]
I think I'll just redo this one in the new repo as this is quick. Testing/merging and possibly improving will still be some time for someone on WMD.

**Comment by dornhege** [comment]
Continued in ros-planning/moveit#42.

**Pull request closed without merging**
