### PR TITLE
Run tests in Travis builds.

### PR DESCRIPTION
**Pull request by hersh**
Please don't merge until Travis build succeeds.

(Then please go ahead. :)

### CODE REVIEW

**Comment by sachinchitta** [comment]
Dave, can you check this - if its not important, we can close it.

**Comment by hersh** [comment]
I'll need to spend some more time with it.  I'm not sure why the tests are failing.

It would be disappointing to just say we're not running any tests at all for moveit_ros.

**Comment by isucan** [comment]
should we close this?

**Comment by hersh** [comment]
I think it's fine to leave open until someone gets time to work on it.

**Comment by sachinchitta** [comment]
I think this can be closed now since its against hydro.

**Pull request closed without merging**
