### PR TITLE
ls

### PR DESCRIPTION
**Pull request by drchrislewis**

### CODE REVIEW

**Comment by adolfo-rt** [comment]
c8fbcd8 seems to be the only relevant changeset. Could you please update the PR to reflect this and keep the history clean?.

**Comment by drchrislewis** [comment]
Adolfo,
    I believe I've compressed all my machinations into a single commit. I
did not know this was possible. I believe the history is now simple and
concise. -Chris

**Comment by adolfo-rt** [comment]
Thanks @drchrislewis.

**Comment by isucan** [comment]
+1

**Comment by davetcoleman** [comment]
I'm testing this now. As an aside, I think a better title, description, and maybe even a screenshot of the GUI change would be helpful.

**Comment by davetcoleman** [comment]
-1 because it expands the width of the plugin GUI too much. Can you push it to the next line below 'Planning Time'? For small screen we really do not want the plugin GUI to be any wider.
Screenshot:
bad_layout

Also, can you make it a whole number only? I don't think its possible to do half a planning attempt.

**Comment by drchrislewis** [comment]
@davetcoleman, Integer input all on a new line. Easy even for a qtnewbe.

**Comment by davetcoleman** [comment]
@drchrislewis did you mean to close this? i'm not sure i understand what you meant in your last comment

**Comment by drchrislewis** [comment]
Dave,
   I'm not sure what my last comment said. I did not intend to close the
pull request. Could someone besides me have done it, or is it automatically
closed with a merge?
I modified the input for the number of planning attempts from float to an
integer.
I also moved the text and input box to the next line just below the
planning time input. I've attached a screenshot.
Do I now need to generate a new pull request?

**Comment by acornacorn** [comment]
Looks like @drchrislewis closed this (maybe accidentally).  You can repoen it or create a new pull request if that is what you want.  Also I don't see the screenshot that you mentioned.  To see all this click on the "View it on GitHub" link in the email.

**Comment by mikeferguson** [comment]
@isucan, we probably want to forward port this to indigo-devel as well?

**Comment by mikeferguson** [comment]
Err, nevermind, looks like it is already there... https://github.com/ros-planning/moveit_ros/commit/86aba90764e5317dee8d3904ea8a6c026e4630e5

**Comment by isucan** [comment]
Yep,  did that.

**Pull request merged**
